name: seal
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - backcall=0.1.0=py38_0
  - blas=1.0=mkl
  - ca-certificates=2020.4.5.1=hecc5488_0
  - certifi=2020.4.5.1=py38h32f6830_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - decorator=4.4.1=py_0
  - easydict=1.9=py_0
  - freetype=2.9.1=h8a8886c_1
  - intel-openmp=2020.0=166
  - ipython=7.12.0=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py38_0
  - jedi=0.16.0=py38_0
  - joblib=0.14.1=py_0
  - jpeg=9b=h024ee3a_2
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - mkl=2020.0=166
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.0.15=py38ha843d7b_0
  - mkl_random=1.1.0=py38h962f231_0
  - ncurses=6.1=he6710b0_1
  - networkx=2.4=py_0
  - ninja=1.9.0=py38hfd86e86_0
  - numpy=1.18.1=py38h4f9e942_0
  - numpy-base=1.18.1=py38hde5b4d6_1
  - olefile=0.46=py_0
  - openssl=1.1.1g=h516909a_0
  - parso=0.6.1=py_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pillow=7.0.0=py38hb39fc2d_0
  - pip=20.0.2=py38_1
  - prompt_toolkit=3.0.3=py_0
  - ptyprocess=0.6.0=py38_0
  - pygments=2.5.2=py_0
  - python=3.8.1=h0371630_1
  - python_abi=3.8=1_cp38
  - pytorch=1.4.0=py3.8_cuda10.1.243_cudnn7.6.3_0
  - readline=7.0=h7b6447c_5
  - scikit-learn=0.22.1=py38hd81dba3_0
  - scipy=1.4.1=py38h0b6359f_0
  - setuptools=45.2.0=py38_0
  - six=1.14.0=py38_0
  - sqlite=3.31.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - torchvision=0.5.0=py38_cu101
  - tqdm=4.42.1=py_0
  - traitlets=4.3.3=py38_0
  - wcwidth=0.1.8=py_0
  - wheel=0.34.2=py38_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - boto==2.49.0
    - boto3==1.12.5
    - botocore==1.15.5
    - chardet==3.0.4
    - cycler==0.10.0
    - docutils==0.15.2
    - gensim==3.8.1
    - googledrivedownloader==0.4
    - h5py==2.10.0
    - idna==2.9
    - imageio==2.8.0
    - isodate==0.6.0
    - jmespath==0.9.4
    - k-gnn==0.0.0
    - kiwisolver==1.1.0
    - llvmlite==0.31.0
    - matplotlib==3.1.3
    - numba==0.48.0
    - pandas==1.0.1
    - plyfile==0.7.1
    - pyparsing==2.4.6
    - python-dateutil==2.8.1
    - pytz==2019.3
    - pywavelets==1.1.1
    - rdflib==4.2.2
    - requests==2.23.0
    - s3transfer==0.3.3
    - scikit-image==0.16.2
    - smart-open==1.9.0
    - torch-cluster==1.4.5
    - torch-geometric==1.4.2
    - torch-scatter==2.0.4
    - torch-sparse==0.6.0
    - torch-spline-conv==1.2.0
    - urllib3==1.25.8
prefix: /home/muhan/anaconda3/envs/seal

